databases:
  - name: psychologiczneiq
    plan: free
    databaseName: psychologiczneiq
    user: psychologiczneiq

services:
  - type: web
    plan: free
    name: psychologiczneiq-backend
    runtime: python
    buildCommand: "./build.sh"
    startCommand: "gunicorn api.wsgi:application"
    envVars:
      - key: DATABASE_URL
        fromDatabase:
          name: psychologiczneiq
          property: connectionString
      - key: SECRET_KEY
        generateValue: true
      - key: WEB_CONCURRENCY
        value: 4