# Generated by Django 4.1.2 on 2022-11-23 12:51

import blog.models
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='post',
            name='author',
            field=models.ForeignKey(default=blog.models.get_default_author, on_delete=django.db.models.deletion.PROTECT, to='blog.author'),
        ),
    ]
