# Generated by Django 4.1.2 on 2022-11-02 15:59

import ckeditor.fields
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('contenttypes', '0002_remove_content_type_name'),
        ('blog', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Grade',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('BookCover', models.FileField(upload_to='')),
                ('General', models.IntegerField()),
            ],
        ),
        migrations.CreateModel(
            name='TextWithImage',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('image', models.FileField(upload_to='')),
                ('rich_text', ckeditor.fields.RichTextField()),
                ('image_position', models.CharField(choices=[('UP', 'up'), ('DO', 'down'), ('LE', 'left'), ('RI', 'right')], max_length=2)),
            ],
        ),
        migrations.CreateModel(
            name='Paragraph',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=300)),
                ('sub_title', models.CharField(max_length=500)),
                ('rich_text', ckeditor.fields.RichTextField()),
                ('post', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='body', related_query_name='body', to='blog.post', to_field='title')),
            ],
        ),
        migrations.CreateModel(
            name='Element',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('grades', models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='blogPosts.grade')),
                ('name', models.ForeignKey(limit_choices_to=models.Q(('app_label', 'blogPosts'), models.Q(('model__startswith', 'element'), _negated=True), models.Q(('model', 'paragraph'), _negated=True)), null=True, on_delete=django.db.models.deletion.CASCADE, to='contenttypes.contenttype')),
                ('paragraphs', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='element', related_query_name='element', to='blogPosts.paragraph')),
                ('text_with_icons', models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='blogPosts.textwithimage')),
            ],
        ),
    ]
