# Generated by Django 4.1.2 on 2022-11-12 19:20

import ckeditor.fields
import django.core.validators
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('blog', '0001_initial'),
        ('contenttypes', '0002_remove_content_type_name'),
    ]

    operations = [
        migrations.CreateModel(
            name='Element',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.ForeignKey(limit_choices_to=models.Q(('app_label', 'blogPosts'), models.Q(('model__startswith', 'element'), _negated=True), models.Q(('model', 'paragraph'), _negated=True), models.Q(('model', 'grade'), _negated=True)), null=True, on_delete=django.db.models.deletion.CASCADE, to='contenttypes.contenttype')),
            ],
        ),
        migrations.CreateModel(
            name='TextWithImage',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('image', models.FileField(blank=True, upload_to='')),
                ('rich_text', ckeditor.fields.RichTextField()),
                ('image_position', models.CharField(blank=True, choices=[('UP', 'up'), ('DO', 'down'), ('LE', 'left'), ('RI', 'right')], max_length=2)),
                ('elements', models.ForeignKey(blank=True, default=1, on_delete=django.db.models.deletion.CASCADE, to='blogPosts.element')),
            ],
        ),
        migrations.CreateModel(
            name='Paragraph',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=300)),
                ('sub_title', models.CharField(blank=True, max_length=500)),
                ('rich_text', ckeditor.fields.RichTextField(blank=True)),
                ('post', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='body', related_query_name='body', to='blog.post', to_field='title')),
            ],
        ),
        migrations.CreateModel(
            name='Grade',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('tag', models.CharField(max_length=300, null=True)),
                ('book_cover', models.FileField(upload_to='')),
                ('general', models.IntegerField(default=0, validators=[django.core.validators.MinValueValidator(0), django.core.validators.MaxValueValidator(5)])),
                ('readability', models.IntegerField(default=0, validators=[django.core.validators.MinValueValidator(0), django.core.validators.MaxValueValidator(5)])),
                ('valence', models.IntegerField(default=0, validators=[django.core.validators.MinValueValidator(0), django.core.validators.MaxValueValidator(5)])),
                ('credibility', models.IntegerField(default=0, validators=[django.core.validators.MinValueValidator(0), django.core.validators.MaxValueValidator(5)])),
                ('knowledge', models.IntegerField(default=0, validators=[django.core.validators.MinValueValidator(0), django.core.validators.MaxValueValidator(5)])),
                ('post', models.OneToOneField(on_delete=django.db.models.deletion.PROTECT, related_name='grade', related_query_name='grade', to='blog.post')),
            ],
        ),
        migrations.AddField(
            model_name='element',
            name='paragraphs',
            field=models.ForeignKey(blank=True, on_delete=django.db.models.deletion.CASCADE, related_name='element', related_query_name='element', to='blogPosts.paragraph'),
        ),
    ]
