# Generated by Django 4.1.2 on 2022-11-02 19:17

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('blogPosts', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='element',
            old_name='grades',
            new_name='grade',
        ),
        migrations.RenameField(
            model_name='element',
            old_name='text_with_icons',
            new_name='textWithImage',
        ),
    ]
