# Generated by Django 4.1.2 on 2022-11-23 14:47

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('blogPosts', '0002_element_multi_columns_tab_button'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='paragraph',
            options={'ordering': ['id']},
        ),
    ]
