# Generated by Django 4.1.2 on 2022-11-02 19:18

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('blogPosts', '0002_rename_grades_element_grade_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='element',
            old_name='textWithImage',
            new_name='textwithimage',
        ),
    ]
