# Generated by Django 4.1.2 on 2022-11-02 22:41

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0003_alter_author_bio'),
        ('contenttypes', '0002_remove_content_type_name'),
        ('blogPosts', '0004_rename_bookcover_grade_book_cover_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='element',
            name='grade',
        ),
        migrations.AddField(
            model_name='grade',
            name='post',
            field=models.ForeignKey(blank=True, default=1, on_delete=django.db.models.deletion.PROTECT, related_name='grade', related_query_name='grade', to='blog.post'),
        ),
        migrations.AlterField(
            model_name='element',
            name='name',
            field=models.ForeignKey(limit_choices_to=models.Q(('app_label', 'blogPosts'), models.Q(('model__startswith', 'element'), _negated=True), models.Q(('model', 'paragraph'), _negated=True), models.Q(('model', 'grade'), _negated=True)), null=True, on_delete=django.db.models.deletion.CASCADE, to='contenttypes.contenttype'),
        ),
        migrations.AlterField(
            model_name='element',
            name='paragraphs',
            field=models.ForeignKey(blank=True, on_delete=django.db.models.deletion.CASCADE, related_name='element', related_query_name='element', to='blogPosts.paragraph'),
        ),
        migrations.AlterField(
            model_name='element',
            name='textwithimage',
            field=models.OneToOneField(blank=True, on_delete=django.db.models.deletion.CASCADE, to='blogPosts.textwithimage'),
        ),
    ]
