# Generated by Django 4.1.2 on 2022-11-02 22:48

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('blogPosts', '0006_remove_element_textwithimage_textwithimage_elements'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='textwithimage',
            name='tag',
        ),
    ]
