# Generated by Django 4.1.2 on 2022-11-02 23:03

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0003_alter_author_bio'),
        ('blogPosts', '0007_remove_textwithimage_tag'),
    ]

    operations = [
        migrations.AlterField(
            model_name='grade',
            name='post',
            field=models.OneToOneField(on_delete=django.db.models.deletion.PROTECT, related_name='grade', related_query_name='grade', to='blog.post'),
        ),
        migrations.AlterField(
            model_name='paragraph',
            name='sub_title',
            field=models.CharField(blank=True, max_length=500),
        ),
    ]
