# Generated by Django 4.1.2 on 2022-11-04 11:06

import ckeditor.fields
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('blogPosts', '0009_alter_textwithimage_image_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='paragraph',
            name='rich_text',
            field=ckeditor.fields.RichTextField(blank=True),
        ),
    ]
